version: '3.8'

services:
  # 1. THE DATABASE
  db:
    image: postgres:16
    container_name: marathon_db
    environment:
      POSTGRES_USER: marathon
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: marathon_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # 2. THE PHOTO STORAGE
  minio:
    image: minio/minio:latest
    container_name: marathon_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

  # 3. YOUR APP (FLASK + YOLO + PARSEQ)
  web:
    build: .
    container_name: marathon_app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - minio
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=marathon
      - PG_PASS=123456
      - PG_DB=marathon_db
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin123
      - S3_BUCKET=marathon
      # SMTP Settings (Fill these in with your email provider info)
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=boracara13@gmail.com
      - SMTP_PASS=wadd qrdx thhi zofd
      - SMTP_FROM=boracara13@gmail.com
    restart: always

volumes:
  pgdata:
  minio_data:
      